-- TT Tours — Seed Data
-- Run after schema.sql to populate all 14 tours.
-- Safe to re-run: conflicts on slug are ignored.

INSERT INTO tours (name, slug, short_description, description, duration, departure_time, return_time, price_vnd, max_group_size, category, difficulty, highlights, included, excluded, meeting_point, thumb_gradient) VALUES

('My Son Sanctuary', 'my-son-sanctuary',
 'Ancient Cham temples hidden in a forested river valley.',
 'Explore the mystical ruins of My Son, a complex of Hindu temples built between the 4th and 14th centuries by the Champa Kingdom. Set deep in a forested valley 70km from Hoi An, this UNESCO World Heritage Site is one of Vietnam''s most important archaeological sites.',
 '4–5 hours', '07:30 AM', '12:30 PM', 550000, 12, 'cultural', 'Easy',
 ARRAY['UNESCO World Heritage Site', 'Over 70 ancient Cham tower temples', 'Expert English-speaking guide', 'Traditional Cham dance performance'],
 ARRAY['Air-conditioned transfer', 'English guide', 'Entrance fees', 'Bottled water'],
 ARRAY['Lunch', 'Personal expenses', 'Tips'],
 'Hotel pickup in Hoi An / Da Nang',
 ARRAY['#5A7A3A', '#8BAA60']),

('Ba Na Hill', 'ba-na-hill',
 'Ride the world-record cable car to the iconic Golden Bridge.',
 'Ba Na Hills is a spectacular mountain resort perched at 1,487m above sea level, just 40km from Da Nang. Take the world''s longest and highest non-stop cable car to reach the top, then explore the extraordinary Golden Bridge held aloft by giant stone hands.',
 '10–12 hours', '07:00 AM', '06:00 PM', 1250000, 15, 'adventure', 'Easy',
 ARRAY['World-record cable car (5,801m)', 'Iconic Golden Bridge', 'French Village & Fantasy Park', 'Panoramic views over Da Nang'],
 ARRAY['Round-trip transfer', 'Cable car tickets', 'Guide', 'Entrance fees'],
 ARRAY['Lunch', 'Rides in Fantasy Park', 'Personal expenses'],
 'Hotel pickup in Hoi An / Da Nang',
 ARRAY['#1E5A7A', '#3A8AAA']),

('Marble Mountain', 'marble-mountain',
 'Five limestone peaks with sacred caves and city views.',
 'The Marble Mountains are a cluster of five marble and limestone hills just south of Da Nang. Climb through sacred Buddhist sanctuaries, hidden caves and reach the summit for sweeping views over China Beach and the South China Sea.',
 '2–3 hours', '08:00 AM', '11:30 AM', 450000, 12, 'cultural', 'Moderate',
 ARRAY['Sacred Buddhist caves and shrines', 'Panoramic views of Da Nang beach', 'Five elemental marble peaks', 'Marble craft village nearby'],
 ARRAY['Transfer', 'Guide', 'Entrance fees'],
 ARRAY['Lift ticket ($2)', 'Personal purchases'],
 'Hotel pickup in Hoi An / Da Nang',
 ARRAY['#8B6F6F', '#C4956A']),

('Cham Island', 'cham-island',
 'Crystal waters, coral reefs and fresh seafood off Hoi An.',
 'Cham Island (Cu Lao Cham) is a UNESCO Biosphere Reserve just 15km offshore from Hoi An. Take a speedboat across the clear South China Sea, then spend the day snorkelling over vibrant coral reefs and enjoying freshly caught seafood.',
 '7–8 hours', '08:00 AM', '04:00 PM', 950000, 15, 'water', 'Easy',
 ARRAY['UNESCO Biosphere Reserve', 'Snorkelling over coral reefs', 'Speedboat crossing', 'Fresh seafood lunch on the beach'],
 ARRAY['Speedboat transfer', 'Snorkel equipment', 'Seafood lunch', 'Life jacket', 'Guide'],
 ARRAY['Extra drinks', 'Personal expenses'],
 'Hoi An boat dock (An Bang Beach)',
 ARRAY['#1A6B7A', '#4AB0C0']),

('Hue City Tour', 'hue-city-tour',
 'Imperial citadel, royal tombs and the dramatic Hai Van Pass.',
 'Journey north to Hue, Vietnam''s ancient imperial capital, via the legendary Hai Van Pass. Explore the vast Imperial Citadel, visit the atmospheric royal tombs of the Nguyen dynasty, and cruise the Perfume River.',
 '10–12 hours', '07:00 AM', '07:00 PM', 1000000, 12, 'cultural', 'Easy',
 ARRAY['Hai Van Pass coastal panorama', 'Imperial Citadel of Hue', 'Nguyen Dynasty royal tombs', 'Thien Mu Pagoda'],
 ARRAY['AC transfer', 'English guide', 'Entrance fees', 'Lunch'],
 ARRAY['Boat trip on Perfume River (+$5)', 'Personal expenses'],
 'Hotel pickup in Hoi An / Da Nang',
 ARRAY['#4A6BA8', '#7895C8']),

('Cham Museum & Han Market', 'cham-museum-han-market',
 'The world''s finest Cham sculpture collection and Da Nang''s bustling market.',
 'Start at the Cham Museum in Da Nang — home to the world''s finest collection of Cham sculpture. Then head to Han Market, Da Nang''s most vibrant local market, where you can sample fresh Vietnamese food and browse local crafts.',
 '3–4 hours', '08:30 AM', '12:30 PM', 500000, 12, 'cultural', 'Easy',
 ARRAY['World-class Cham sculpture collection', 'Da Nang''s oldest covered market', 'Local street food tasting', 'Expert cultural commentary'],
 ARRAY['Transfer', 'Guide', 'Cham Museum entrance'],
 ARRAY['Food purchases', 'Shopping'],
 'Hotel pickup in Da Nang / Hoi An',
 ARRAY['#7A5A9A', '#B08AC0']),

('Basket Boat Tour', 'basket-boat-tour',
 'Spin through coconut palm waterways in a traditional coracle.',
 'Experience one of Vietnam''s most unique activities: a ride in a traditional round bamboo basket boat through the enchanting coconut palm waterways of Cam Thanh village.',
 '2 hours', '08:00 AM', '10:00 AM', 350000, 10, 'nature', 'Easy',
 ARRAY['Traditional bamboo coracle ride', 'Coconut palm water forest', 'Crab and fish catching demo', 'Fresh coconut on the bank'],
 ARRAY['Round-trip transfer', 'Boat & life jacket', 'Local guide'],
 ARRAY['Tips for boatman (appreciated)'],
 'Hotel pickup in Hoi An',
 ARRAY['#3A8A60', '#70BF90']),

('Vespa Tour', 'vespa-tour',
 'Pillion through hidden laneways and street food spots on a vintage Vespa.',
 'Hop on the back of a vintage Vespa scooter with your expert local guide-driver and explore Hoi An''s old quarter, surrounding villages and hidden eating spots that most tourists never find.',
 '3–4 hours', '05:00 PM', '09:00 PM', 700000, 6, 'food', 'Easy',
 ARRAY['Vintage Vespa ride through old Hoi An', '4–5 authentic local food stops', 'Evening lantern atmosphere', 'Off-the-beaten-track laneways'],
 ARRAY['Vespa & driver', 'Helmet', 'Food tastings at stops', 'Water'],
 ARRAY['Full meals', 'Drinks beyond tastings'],
 'Hoi An Old Town (meeting point confirmed on booking)',
 ARRAY['#C45A3A', '#E87A60']),

('Diving Tour', 'diving-tour',
 'Discover vibrant reefs of the South China Sea with PADI instructors.',
 'Dive into the crystal-clear waters around Cham Island. Whether you''re a certified diver or a complete beginner, our PADI-certified instructors will guide you safely through colourful coral gardens and diverse marine life.',
 '5–6 hours', '07:30 AM', '01:00 PM', 1200000, 8, 'water', 'Moderate',
 ARRAY['PADI-certified dive instructors', 'Two dives at separate reef sites', 'Marine biodiversity briefing', 'Discovery dive option for beginners'],
 ARRAY['Speedboat', 'All diving equipment', 'PADI instructor', '2 dives', 'Snacks'],
 ARRAY['Dive certification fee (if needed)', 'Underwater camera rental'],
 'Hoi An boat dock',
 ARRAY['#1A4A8A', '#3A7ABF']),

('Hoi An Bike Tour', 'hoi-an-bike-tour',
 'Cycle through rice paddies and riverside villages at sunrise.',
 'Explore the countryside surrounding Hoi An''s ancient town on two wheels. Pedal along quiet paths through emerald rice paddies, cross wooden bridges, and visit a local carpenter''s workshop.',
 '3–4 hours', '07:00 AM', '11:00 AM', 450000, 10, 'nature', 'Easy',
 ARRAY['Rice paddy & village cycling route', 'Riverside café stop', 'Local carpenter workshop visit', 'Scenic Thu Bon riverside'],
 ARRAY['Bicycle', 'Helmet', 'Guide', 'Vietnamese coffee stop'],
 ARRAY['Personal food & drink purchases'],
 'Hoi An Old Town (confirmed on booking)',
 ARRAY['#4A8A4A', '#7BC07B']),

('Easy Rider Tour', 'easy-rider-tour',
 'Hit the open road with a local guide on the back of a motorbike.',
 'Ride pillion with your passionate local guide through the farming villages west of town, into the hills to see pepper farms and cassava fields, past water buffalo working the paddies.',
 '4–5 hours', '08:00 AM', '01:00 PM', 800000, 6, 'adventure', 'Easy',
 ARRAY['Off-road motorbike countryside ride', 'Local farming village visits', 'Home-cooked village lunch', 'Authentic local guide commentary'],
 ARRAY['Motorbike & driver-guide', 'Helmet', 'Lunch at local home'],
 ARRAY['Drinks', 'Tips'],
 'Hotel pickup in Hoi An',
 ARRAY['#8A4A1A', '#C08040']),

('Thanh Ha Pottery Village', 'thanh-ha-pottery-village',
 '500-year-old pottery tradition — try your hand at the wheel.',
 'Just 3km from Hoi An''s Old Town, Thanh Ha is a village with 500 years of unbroken pottery-making tradition. Watch master craftsmen and try to create a pot under their expert guidance.',
 '2–3 hours', '08:30 AM', '11:30 AM', 400000, 12, 'cultural', 'Easy',
 ARRAY['500-year pottery tradition', 'Hands-on pottery wheel experience', 'Miniature Ancient Town replica', 'Take your creation home'],
 ARRAY['Bicycle or transfer', 'Entrance fee', 'Clay lesson', 'Guide'],
 ARRAY['Pottery purchases', 'Firing/shipping of your piece'],
 'Hotel pickup in Hoi An',
 ARRAY['#C47A3A', '#E0A060']),

('Tra Que Herb Village', 'tra-que-herb-village',
 'Learn traditional farming and cook with freshly-picked herbs.',
 'Tra Que is a small organic farming village just outside Hoi An. Join the farmers for a morning, learn to plough and sow using traditional methods, then pick your own fresh herbs for a hands-on Vietnamese cooking lesson.',
 '3–4 hours', '08:00 AM', '12:00 PM', 450000, 10, 'food', 'Easy',
 ARRAY['Organic herb and vegetable farming', 'Traditional ploughing & watering demo', 'Hands-on Vietnamese cooking class', 'Eat the meal you cook'],
 ARRAY['Bicycle or transfer', 'Farming activity', 'Cooking class', 'Lunch you cook', 'Guide'],
 ARRAY['Drinks beyond water'],
 'Hotel pickup in Hoi An',
 ARRAY['#4A7A3A', '#80B060']),

('Marble Mountain & Da Nang City', 'marble-mountain-danang-city',
 'Sacred caves, Buddha statues and Da Nang''s famous Dragon Bridge.',
 'A perfect half-day combining the natural and urban highlights of Da Nang. Begin at the Marble Mountains then drive into Da Nang city for the famous Dragon Bridge, the iconic Lady Buddha at Son Tra Peninsula, and a stroll along the Han River promenade.',
 '4–5 hours', '08:00 AM', '01:00 PM', 650000, 12, 'cultural', 'Moderate',
 ARRAY['Marble Mountain caves and pagodas', 'Giant Lady Buddha at Son Tra', 'Dragon Bridge & Han River', 'Non Nuoc beach views'],
 ARRAY['AC transfer', 'Guide', 'Marble Mountain entrance'],
 ARRAY['Lift ticket at Marble Mountain', 'Lunch'],
 'Hotel pickup in Hoi An / Da Nang',
 ARRAY['#5A6A8A', '#8090B0'])
ON CONFLICT (slug) DO NOTHING;
