import { Tour } from '@/types';

export const TOURS: Tour[] = [
  {
    id: '1',
    name: 'My Son Sanctuary',
    slug: 'my-son-sanctuary',
    shortDescription: 'Ancient Cham temples hidden in a forested river valley.',
    description:
      'Explore the mystical ruins of My Son, a complex of Hindu temples built between the 4th and 14th centuries by the Champa Kingdom. Set deep in a forested valley 70km from Hoi An, this UNESCO World Heritage Site is one of Vietnam\'s most important archaeological sites. Your expert guide will reveal the history, astronomy and symbolism carved into every stone.',
    duration: '4–5 hours',
    departureTime: '07:30 AM',
    returnTime: '12:30 PM',
    priceUsd: 22,
    maxGroupSize: 12,
    category: 'cultural',
    difficulty: 'Easy',
    highlights: [
      'UNESCO World Heritage Site',
      'Over 70 ancient Cham tower temples',
      'Expert English-speaking guide',
      'Traditional Cham dance performance',
    ],
    included: ['Air-conditioned transfer', 'English guide', 'Entrance fees', 'Bottled water'],
    excluded: ['Lunch', 'Personal expenses', 'Tips'],
    meetingPoint: 'Hotel pickup in Hoi An / Da Nang',
    thumbGradient: ['#5A7A3A', '#8BAA60'],
    isActive: true,
  },
  {
    id: '2',
    name: 'Ba Na Hill',
    slug: 'ba-na-hill',
    shortDescription: 'Ride the world-record cable car to the iconic Golden Bridge.',
    description:
      'Ba Na Hills is a spectacular mountain resort perched at 1,487m above sea level, just 40km from Da Nang. Take the world\'s longest and highest non-stop cable car to reach the top, then explore the extraordinary Golden Bridge — held aloft by giant stone hands — the French Village, Fantasy Park and stunning panoramic views over the entire region.',
    duration: '10–12 hours',
    departureTime: '07:00 AM',
    returnTime: '06:00 PM',
    priceUsd: 50,
    maxGroupSize: 15,
    category: 'adventure',
    difficulty: 'Easy',
    highlights: [
      'World-record cable car (5,801m)',
      'Iconic Golden Bridge',
      'French Village & Fantasy Park',
      'Panoramic views over Da Nang',
    ],
    included: ['Round-trip transfer', 'Cable car tickets', 'Guide', 'Entrance fees'],
    excluded: ['Lunch', 'Rides in Fantasy Park', 'Personal expenses'],
    meetingPoint: 'Hotel pickup in Hoi An / Da Nang',
    thumbGradient: ['#1E5A7A', '#3A8AAA'],
    isActive: true,
  },
  {
    id: '3',
    name: 'Marble Mountain',
    slug: 'marble-mountain',
    shortDescription: 'Five limestone peaks with sacred caves and city views.',
    description:
      'The Marble Mountains are a cluster of five marble and limestone hills just south of Da Nang. Each hill is named after one of the five elements: water, wood, fire, metal and earth. Climb through sacred Buddhist sanctuaries, hidden caves and tunnels, and reach the summit for sweeping views over China Beach and the South China Sea. Combine with a visit to the nearby marble carving workshops.',
    duration: '2–3 hours',
    departureTime: '08:00 AM',
    returnTime: '11:30 AM',
    priceUsd: 18,
    maxGroupSize: 12,
    category: 'cultural',
    difficulty: 'Moderate',
    highlights: [
      'Sacred Buddhist caves and shrines',
      'Panoramic views of Da Nang beach',
      'Five elemental marble peaks',
      'Marble craft village nearby',
    ],
    included: ['Transfer', 'Guide', 'Entrance fees'],
    excluded: ['Lift ticket ($2)', 'Personal purchases'],
    meetingPoint: 'Hotel pickup in Hoi An / Da Nang',
    thumbGradient: ['#8B6F6F', '#C4956A'],
    isActive: true,
  },
  {
    id: '4',
    name: 'Cham Island',
    slug: 'cham-island',
    shortDescription: 'Crystal waters, coral reefs and fresh seafood off Hoi An.',
    description:
      'Cham Island (Cu Lao Cham) is a UNESCO Biosphere Reserve just 15km offshore from Hoi An. Take a speedboat across the clear South China Sea, then spend the day snorkelling over vibrant coral reefs teeming with tropical fish, swimming in hidden coves, and enjoying freshly caught seafood on the beach. The island\'s waters are among the most pristine in central Vietnam.',
    duration: '7–8 hours',
    departureTime: '08:00 AM',
    returnTime: '04:00 PM',
    priceUsd: 38,
    maxGroupSize: 15,
    category: 'water',
    difficulty: 'Easy',
    highlights: [
      'UNESCO Biosphere Reserve',
      'Snorkelling over coral reefs',
      'Speedboat crossing',
      'Fresh seafood lunch on the beach',
    ],
    included: ['Speedboat transfer', 'Snorkel equipment', 'Seafood lunch', 'Life jacket', 'Guide'],
    excluded: ['Extra drinks', 'Personal expenses'],
    meetingPoint: 'Hoi An boat dock (An Bang Beach)',
    thumbGradient: ['#1A6B7A', '#4AB0C0'],
    isActive: true,
  },
  {
    id: '5',
    name: 'Hue City Tour',
    slug: 'hue-city-tour',
    shortDescription: 'Imperial citadel, royal tombs and the dramatic Hai Van Pass.',
    description:
      'Journey north to Hue, Vietnam\'s ancient imperial capital, via the legendary Hai Van Pass — a mountain road with jaw-dropping views of the Pacific coastline that became famous after the Top Gear Vietnam special. In Hue, explore the vast Imperial Citadel, visit the atmospheric royal tombs of the Nguyen dynasty, and cruise the Perfume River.',
    duration: '10–12 hours',
    departureTime: '07:00 AM',
    returnTime: '07:00 PM',
    priceUsd: 40,
    maxGroupSize: 12,
    category: 'cultural',
    difficulty: 'Easy',
    highlights: [
      'Hai Van Pass coastal panorama',
      'Imperial Citadel of Hue',
      'Nguyen Dynasty royal tombs',
      'Thien Mu Pagoda',
    ],
    included: ['AC transfer', 'English guide', 'Entrance fees', 'Lunch'],
    excluded: ['Boat trip on Perfume River (+$5)', 'Personal expenses'],
    meetingPoint: 'Hotel pickup in Hoi An / Da Nang',
    thumbGradient: ['#4A6BA8', '#7895C8'],
    isActive: true,
  },
  {
    id: '6',
    name: 'Cham Museum & Han Market',
    slug: 'cham-museum-han-market',
    shortDescription: "The world's finest Cham sculpture collection and Da Nang's bustling market.",
    description:
      'Start at the Cham Museum in Da Nang — home to the world\'s finest collection of Cham sculpture, spanning the 7th–15th centuries. Marvel at intricately carved deities, linga, and altars. Then head to Han Market, Da Nang\'s most vibrant local market, where you can sample fresh Vietnamese food, browse local crafts and pick up unique souvenirs.',
    duration: '3–4 hours',
    departureTime: '08:30 AM',
    returnTime: '12:30 PM',
    priceUsd: 20,
    maxGroupSize: 12,
    category: 'cultural',
    difficulty: 'Easy',
    highlights: [
      'World-class Cham sculpture collection',
      "Da Nang's oldest covered market",
      'Local street food tasting',
      'Expert cultural commentary',
    ],
    included: ['Transfer', 'Guide', 'Cham Museum entrance'],
    excluded: ['Food purchases', 'Shopping'],
    meetingPoint: 'Hotel pickup in Da Nang / Hoi An',
    thumbGradient: ['#7A5A9A', '#B08AC0'],
    isActive: true,
  },
  {
    id: '7',
    name: 'Basket Boat Tour',
    slug: 'basket-boat-tour',
    shortDescription: 'Spin through coconut palm waterways in a traditional coracle.',
    description:
      'Experience one of Vietnam\'s most unique activities: a ride in a traditional round bamboo basket boat through the enchanting coconut palm waterways of Cam Thanh village. Your local boatman will expertally spin, row and dance the coracle through the maze of water palms. Learn to catch crabs and fish, then enjoy a refreshing coconut on the riverbank.',
    duration: '2 hours',
    departureTime: '08:00 AM',
    returnTime: '10:00 AM',
    priceUsd: 15,
    maxGroupSize: 10,
    category: 'nature',
    difficulty: 'Easy',
    highlights: [
      'Traditional bamboo coracle ride',
      'Coconut palm water forest',
      'Crab and fish catching demo',
      'Fresh coconut on the bank',
    ],
    included: ['Round-trip transfer', 'Boat & life jacket', 'Local guide'],
    excluded: ['Tips for boatman (appreciated)'],
    meetingPoint: 'Hotel pickup in Hoi An',
    thumbGradient: ['#3A8A60', '#70BF90'],
    isActive: true,
  },
  {
    id: '8',
    name: 'Vespa Tour',
    slug: 'vespa-tour',
    shortDescription: 'Pillion through hidden laneways and street food spots on a vintage Vespa.',
    description:
      "Hop on the back of a vintage Vespa scooter with your expert local guide-driver and explore Hoi An's old quarter, surrounding villages and hidden eating spots that most tourists never find. Stop at a local market, try hand-made bánh mì, slurp cao lầu noodles at a family restaurant, and watch lanterns light up the ancient town as evening falls.",
    duration: '3–4 hours',
    departureTime: '05:00 PM',
    returnTime: '09:00 PM',
    priceUsd: 28,
    maxGroupSize: 6,
    category: 'food',
    difficulty: 'Easy',
    highlights: [
      'Vintage Vespa ride through old Hoi An',
      '4–5 authentic local food stops',
      'Evening lantern atmosphere',
      'Off-the-beaten-track laneways',
    ],
    included: ['Vespa & driver', 'Helmet', 'Food tastings at stops', 'Water'],
    excluded: ['Full meals', 'Drinks beyond tastings'],
    meetingPoint: 'Hoi An Old Town (meeting point confirmed on booking)',
    thumbGradient: ['#C45A3A', '#E87A60'],
    isActive: true,
  },
  {
    id: '9',
    name: 'Diving Tour',
    slug: 'diving-tour',
    shortDescription: 'Discover vibrant reefs of the South China Sea with PADI instructors.',
    description:
      "Dive into the crystal-clear waters around Cham Island, one of Vietnam's best-kept marine secrets. Whether you're a certified diver or a complete beginner, our PADI-certified instructors will guide you safely through colourful coral gardens, sea grass beds and diverse marine life including turtles, seahorses and reef sharks. Discovery dives available for first-timers.",
    duration: '5–6 hours',
    departureTime: '07:30 AM',
    returnTime: '01:00 PM',
    priceUsd: 48,
    maxGroupSize: 8,
    category: 'water',
    difficulty: 'Moderate',
    highlights: [
      'PADI-certified dive instructors',
      'Two dives at separate reef sites',
      'Marine biodiversity briefing',
      'Discovery dive option for beginners',
    ],
    included: ['Speedboat', 'All diving equipment', 'PADI instructor', '2 dives', 'Snacks'],
    excluded: ['Dive certification fee (if needed)', 'Underwater camera rental'],
    meetingPoint: 'Hoi An boat dock',
    thumbGradient: ['#1A4A8A', '#3A7ABF'],
    isActive: true,
  },
  {
    id: '10',
    name: 'Hoi An Bike Tour',
    slug: 'hoi-an-bike-tour',
    shortDescription: 'Cycle through rice paddies and riverside villages at sunrise.',
    description:
      'Explore the countryside surrounding Hoi An\'s ancient town on two wheels at the perfect pace. Pedal along quiet paths through emerald rice paddies, cross wooden bridges, visit a local carpenter\'s workshop, stop at a riverside café for Vietnamese coffee, and pass through the small fishing hamlets that line the Thu Bon River. Suitable for all fitness levels.',
    duration: '3–4 hours',
    departureTime: '07:00 AM',
    returnTime: '11:00 AM',
    priceUsd: 18,
    maxGroupSize: 10,
    category: 'nature',
    difficulty: 'Easy',
    highlights: [
      'Rice paddy & village cycling route',
      'Riverside café stop',
      'Local carpenter workshop visit',
      'Scenic Thu Bon riverside',
    ],
    included: ['Bicycle', 'Helmet', 'Guide', 'Vietnamese coffee stop'],
    excluded: ['Personal food & drink purchases'],
    meetingPoint: 'Hoi An Old Town (confirmed on booking)',
    thumbGradient: ['#4A8A4A', '#7BC07B'],
    isActive: true,
  },
  {
    id: '11',
    name: 'Easy Rider Tour',
    slug: 'easy-rider-tour',
    shortDescription: 'Hit the open road with a local guide on the back of a motorbike.',
    description:
      "Vietnam's Easy Rider tradition was born in the hills of Dalat, but Hoi An has its own legendary version. Ride pillion with your passionate local guide through the farming villages west of town, into the hills to see pepper farms and cassava fields, past water buffalo working the paddies, and stop at local homes to meet families and share a meal — no tour bus in sight.",
    duration: '4–5 hours',
    departureTime: '08:00 AM',
    returnTime: '01:00 PM',
    priceUsd: 32,
    maxGroupSize: 6,
    category: 'adventure',
    difficulty: 'Easy',
    highlights: [
      'Off-road motorbike countryside ride',
      'Local farming village visits',
      'Home-cooked village lunch',
      'Authentic local guide commentary',
    ],
    included: ['Motorbike & driver-guide', 'Helmet', 'Lunch at local home'],
    excluded: ['Drinks', 'Tips'],
    meetingPoint: 'Hotel pickup in Hoi An',
    thumbGradient: ['#8A4A1A', '#C08040'],
    isActive: true,
  },
  {
    id: '12',
    name: 'Thanh Ha Pottery Village',
    slug: 'thanh-ha-pottery-village',
    shortDescription: '500-year-old pottery tradition — try your hand at the wheel.',
    description:
      'Just 3km from Hoi An\'s Old Town, Thanh Ha is a village with 500 years of unbroken pottery-making tradition. Watch master craftsmen shape clay on traditional foot-powered wheels, then get your own hands in the clay and try to create a pot, bowl or animal under their expert guidance. Browse the terracotta sculptures and browse the miniature clay Hoi An Ancient Town.',
    duration: '2–3 hours',
    departureTime: '08:30 AM',
    returnTime: '11:30 AM',
    priceUsd: 16,
    maxGroupSize: 12,
    category: 'cultural',
    difficulty: 'Easy',
    highlights: [
      '500-year pottery tradition',
      'Hands-on pottery wheel experience',
      'Miniature Ancient Town replica',
      'Take your creation home',
    ],
    included: ['Bicycle or transfer', 'Entrance fee', 'Clay lesson', 'Guide'],
    excluded: ['Pottery purchases', 'Firing/shipping of your piece'],
    meetingPoint: 'Hotel pickup in Hoi An',
    thumbGradient: ['#C47A3A', '#E0A060'],
    isActive: true,
  },
  {
    id: '13',
    name: 'Tra Que Herb Village',
    slug: 'tra-que-herb-village',
    shortDescription: 'Learn traditional farming and cook with freshly-picked herbs.',
    description:
      'Tra Que is a small organic farming village just outside Hoi An where generations of farmers have grown herbs and vegetables in the rich soil near the Tra Que river. Join the farmers for a morning, learn to plough, rake, sow and water using traditional methods, then pick your own fresh herbs and vegetables for a hands-on Vietnamese cooking lesson — finishing with a meal you\'ve made yourself.',
    duration: '3–4 hours',
    departureTime: '08:00 AM',
    returnTime: '12:00 PM',
    priceUsd: 18,
    maxGroupSize: 10,
    category: 'food',
    difficulty: 'Easy',
    highlights: [
      'Organic herb and vegetable farming',
      'Traditional ploughing & watering demo',
      'Hands-on Vietnamese cooking class',
      'Eat the meal you cook',
    ],
    included: ['Bicycle or transfer', 'Farming activity', 'Cooking class', 'Lunch you cook', 'Guide'],
    excluded: ['Drinks beyond water'],
    meetingPoint: 'Hotel pickup in Hoi An',
    thumbGradient: ['#4A7A3A', '#80B060'],
    isActive: true,
  },
  {
    id: '14',
    name: 'Marble Mountain & Da Nang City',
    slug: 'marble-mountain-danang-city',
    shortDescription: 'Sacred caves, Buddha statues and Da Nang\'s famous Dragon Bridge.',
    description:
      'A perfect half-day combining the natural and urban highlights of Da Nang. Begin at the Marble Mountains — five limestone peaks named after the five elements — to explore Buddhist sanctuaries, sacred caves and sweeping beach views. Then drive into Da Nang city for the famous Dragon Bridge (breathes fire on weekend evenings), the iconic Lady Buddha at Son Tra Peninsula, and a stroll along the Han River promenade.',
    duration: '4–5 hours',
    departureTime: '08:00 AM',
    returnTime: '01:00 PM',
    priceUsd: 25,
    maxGroupSize: 12,
    category: 'cultural',
    difficulty: 'Moderate',
    highlights: [
      'Marble Mountain caves and pagodas',
      'Giant Lady Buddha at Son Tra',
      'Dragon Bridge & Han River',
      'Non Nuoc beach views',
    ],
    included: ['AC transfer', 'Guide', 'Marble Mountain entrance'],
    excluded: ['Lift ticket at Marble Mountain', 'Lunch'],
    meetingPoint: 'Hotel pickup in Hoi An / Da Nang',
    thumbGradient: ['#5A6A8A', '#8090B0'],
    isActive: true,
  },
];

export const TOUR_BY_SLUG = Object.fromEntries(TOURS.map((t) => [t.slug, t]));
export const TOUR_BY_ID = Object.fromEntries(TOURS.map((t) => [t.id, t]));
